In [20]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.metrics import classification_report
from category_encoders import TargetEncoder
from sklearn.tree import DecisionTreeClassifier,DecisionTreeRegressor

In [21]:
df = pd.read_csv("sales_data.csv")

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Product_ID            1000 non-null   int64
 1   Sale_Date             1000 non-null   object
 2   Sales_Rep             1000 non-null   object
 3   Region                1000 non-null   object
 4   Sales_Amount          1000 non-null   float64
 5   Quantity_Sold         1000 non-null   int64
 6   Product_Category      1000 non-null   object
 7   Unit_Cost             1000 non-null   float64
 8   Unit_Price            1000 non-null   float64
 9   Customer_Type         1000 non-null   object
 10  Discount              1000 non-null   float64
 11  Payment_Method        1000 non-null   object
 12  Sales_Channel         1000 non-null   object
 13  Region_and_Sales_Rep  1000 non-null   object
dtypes: float64(4), int64(2), object(8)
memory usage: 109.5+ KB

In [23]:
df.duplicated().any()

np.False_

In [24]:
df.nunique()

Product_ID               100
Sale_Date                340
Sales_Rep                  5
Region                     4
Sales_Amount             998
Quantity_Sold             49
Product_Category           4
Unit_Cost                998
Unit_Price              1000
Customer_Type              2
Discount                  31
Payment_Method             3
Sales_Channel              2
Region_and_Sales_Rep      20
dtype: int64

In [25]:
df = df.drop(columns= ["Sale_Date","Region","Sales_Rep"])

In [26]:
df.head()

,Product_ID,Sales_Amount,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type,Discount,Payment_Method,Sales_Channel,Region_and_Sales_Rep
0,1052,5053.97,18,Furniture,152.75,267.22,Returning,0.09,Cash,Online,North-Bob
1,1093,4384.02,17,Furniture,3816.39,4209.44,Returning,0.11,Cash,Retail,West-Bob
2,1015,4631.23,30,Food,261.56,371.40,Returning,0.20,Bank Transfer,Retail,South-David
3,1072,2167.94,39,Clothing,4330.03,4467.75,New,0.02,Credit Card,Retail,South-Bob
4,1061,3750.20,13,Electronics,637.37,692.71,New,0.08,Credit Card,Online,East-Charlie

In [27]:
df["Product_ID"] = df["Product_ID"].astype("str")

In [28]:
x = df.drop(columns = "Sales_Amount")
y = df.Sales_Amount

In [29]:
xtrain, xtest, ytrain, ytest = train_test_split(x,y,train_size= 0.8,random_state=42)

In [30]:
num_col = x.select_dtypes(include= "number")
cat_col = x.select_dtypes(exclude= "number")

In [31]:
cat_col.nunique()

Product_ID              100
Product_Category          4
Customer_Type             2
Payment_Method            3
Sales_Channel             2
Region_and_Sales_Rep     20
dtype: int64

In [32]:
x.Product_ID.nunique()

100

In [33]:
# encoding = TargetEncoder()
# encoding.fit_transform(xtrain.Product_ID,ytrain)

In [34]:
encoding = TargetEncoder(cols = "Product_ID")
xtrain = encoding.fit_transform(xtrain,ytrain)

In [35]:
xtrain.head()

,Product_ID,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type,Discount,Payment_Method,Sales_Channel,Region_and_Sales_Rep
29,4761.797474,1,Furniture,3290.89,3317.75,Returning,0.17,Bank Transfer,Online,West-Alice
535,4977.267950,25,Electronics,1330.62,1543.69,New,0.27,Credit Card,Online,East-Eve
695,4697.012117,27,Furniture,3624.97,3836.52,New,0.08,Cash,Online,West-Alice
557,5143.163411,9,Clothing,335.82,498.31,New,0.26,Cash,Retail,South-David
836,4777.849710,20,Food,668.11,803.49,New,0.21,Bank Transfer,Online,East-Bob

In [36]:
ytrain.value_counts()

Sales_Amount
7946.69    2
6801.71    1
9220.94    1
6994.66    1
6699.34    1
          ..
3517.40    1
8499.41    1
4703.59    1
2106.06    1
6360.67    1
Name: count, Length: 799, dtype: int64

In [37]:
preprocessing = ColumnTransformer(
    transformers=[
        ("onehot",OneHotEncoder(),["Product_Category","Customer_Type","Payment_Method","Sales_Channel"]),
        ("traget",TargetEncoder(),["Product_ID","Region_and_Sales_Rep"])
    ]
)

In [38]:
main_pipeline = Pipeline(
    steps = [
        ("pre",preprocessing),
        ("model",DecisionTreeRegressor())
    ]
)
main_pipeline.fit(xtrain,ytrain)

Pipeline(steps=[('pre',
                 ColumnTransformer(transformers=[('onehot', OneHotEncoder(),
                                                  ['Product_Category',
                                                   'Customer_Type',
                                                   'Payment_Method',
                                                   'Sales_Channel']),
                                                 ('traget', TargetEncoder(),
                                                  ['Product_ID',
                                                   'Region_and_Sales_Rep'])])),
                ('model', DecisionTreeRegressor())])